### ISSUE TITLE
Add "alut" to this package?

### ISSUE THREAD

**Issue by sunnystormy** [jpernst/openal-rs#24]
ALUT adds some helper methods for initializing audio files and creating/binding a buffer. Is there a way you can get that added inside of this package so users don't have to resort to the boilerplate "alc" conventions?

**Comment by jpernst** [comment]
I've never used ALUT before, but from what I'm seeing in the API documentation, it could just be reimplemented in rust rather straightforwardly using crates like `hound`, `vorbisfile`, `opusfile-rs`, etc. I'd rather not introduce another dependency on a native lib, but would be open to cargo features that optionally enable some convenience functions for various formats. My efforts are currently focused elsewhere, but I'd be happy to review any PRs if someone is interested in contributing those features.

**Comment by sunnystormy** [comment]
Well, the advantage of using ALUT has to do with making it easier for loading and playing ".WAV" files. Is there a way you could provide a .WAV loading example inside of the tests? I think that would help users jump-start their usage of this library, as well as give them ideas about incorporating other ones like vorbis-rs (inside of their own projects).

**Comment by sunnystormy** [comment]
*Bump*

I'm actually in the process of creating a .WAV loader for this from scratch based upon [this tutorial](http://www.dunsanyinteractive.com/blog/oliver/?p=72). Some of the data types are different (because Rust handles chars differently than C), but if you have any pointers, I'd appreciate your help!

**Comment by jpernst** [comment]
The WAV format isn't too bad. The main tip I have is to just make sure you handle the potential that the RIFF chunks can be in any order. The source for hound is also probably a good reference: https://github.com/ruuda/hound

**Comment by sunnystormy** [comment]
Huh! This library makes what I'm trying to do much easier. Thank you for making me aware of it! : )

**Comment by sunnystormy** [comment]
@jpernst You can go ahead and close this ticket. I've figured out how to play .WAV files using Hound and openal-rs. :)
