### ISSUE TITLE
Compiling for MinGW-W64

### ISSUE THREAD

**Issue by phaazon** [jpernst/openal-rs#25]
I’ve been trying to compile the crate on mingw-w64 for hours. I haven’t found a way to make it through with the crates.io crate, so I downloaded `openal-rs`, add a local override to my project and changed the link target from `#[link(name = "openal32")]` to `#[link(name = "openal")]`, because that’s what `pkg-config` expects if you pass it `--libs openal`.

After our talk on IRC, you uploaded an upper-case version that will work for the native Windows installation but not for MinGW. What can we do about that?

**Comment by jpernst** [comment]
Honestly I'm not sure. MinGW is a bit strange in that it's windows, but acts like unix. I'm not quite sure how to handle both that and the MSVC case. Perhaps there's a more specific cfg attribute that can be used; I'll look into it.

**Comment by phaazon** [comment]
Yeah, that’s what I thought as well. I’ll keep track of this too.

**Comment by jpernst** [comment]
Ok, I think I've found a possible solution. Could you try pulling the latest from git and seeing if it works under mingw?

**Comment by phaazon** [comment]
I don’t have it anymore – released. I’ll try in my VM when I find enough spare time though. Thank you very much. :)

**Comment by jpernst** [comment]
Closing this for now since I'm redoing this lib completely.

**Comment by phaazon** [comment]
Wait what do you mean redoing this lib completely? Will it change the interface?

**Comment by jpernst** [comment]
The raw FFI bindings will still be available as before, but I'm completely redoing the high-level interface, since the previous version was both incomplete and unsound. While I'm at it I'm also going to expose most documented extensions including the EFX suite and the software loopback device, so openal-rs will be able to feed its audio into SDL2 or whatever other platform lib.

**Comment by phaazon** [comment]
Ok, I’ll follow along upstream, since I have a project I’m working on using openal-rs ;) – btw, it’d be nice to have a better name on crates.io, but I don’t know whether it’s possible. I wrote the `al` Haskell binding to OpenAL, I know that kind of stuff can get tedious :). Good luck!

**Comment by jpernst** [comment]
I was never quite happy with the name either, honestly. Since I'm doing a complete rewrite, I guess now is the time to change, so I've renamed the high level api to `alto` and moved the ffi stuff into `al-sys`

**Comment by phaazon** [comment]
Interesting; I’ll be looking forward to it.
