### ISSUE TITLE
Need alcGetCurrentContext() and alcGetContextsDevice() for library I'm writing.

### ISSUE THREAD

**Issue by sunnystormy** [jpernst/openal-rs#28]
Hello!

I need those two methods in order to properly implement the destructor for my Rust library. Is there a way that they can be added, please?

Thank you!

**Comment by jpernst** [comment]
The raw alc functions are exposed by the lib in the `ffi` module and should be usable. I'm not sure how to expose them safely, since doing so would violate the API's invariants.

**Comment by sunnystormy** [comment]
I'm trying to use those methods, but am getting type issues because of the *const. Writing a method like

`alc::ffi::alcCloseDevice(alc::ffi::alcGetContextsDevice(alc::ffi::alcGetCurrentContext()));
`

Still leads to the device not getting closed when the class goes out of scope.

**Comment by jpernst** [comment]
According to the openal reference, a device cannot be closed until all contexts/buffers associated with the device have first been destroyed.

**Comment by sunnystormy** [comment]
Yup. Another issue I'm having is the ability to copy buffers and sources into instances of my class. Otherwise, I'm going to have to generate them on the spot, which can be kind of tedious. Is there a way you can implement those traits?

**Comment by jpernst** [comment]
If you need to share a buffer among several classes I'd recommend just putting it an an `Arc`. Buffers and sources have internal state that would be tricky to copy.

**Comment by sunnystormy** [comment]
I'm sorry, what I meant was having a member variable inside of my class that has a copy of the buffer. For some reason, whenever I try to do this, Rust complains. The last thing I want to do is have to recreate contexts/buffers whenever I want to alter the state of my audio.

**Comment by jpernst** [comment]
I still don't quite understand what you're trying to do; I'd need a specific code example.

**Comment by sunnystormy** [comment]
I'll provide that sometime tomorrow. It's late here, but will be happy to share it with you once I've gotten some rest. :)

**Comment by sunnystormy** [comment]
Opened a repo [here](https://github.com/sunnystormy/audionode-rs). Please take a look at the lib and give me your thoughts. As I said before, the buffer/source isn't remaining in memory to do what I need it to.

**Comment by jpernst** [comment]
Ok, I see what's wrong now. Unfortuantely, I'm not sure it can be easily fixed without redesigning openal-rs completely. I inherited this crate from the original author before rust 1.0 even came out, but my interest was only ever really in the raw FFI bindings, not the high-level wrapper which I never even used. I'd recommend just skipping the high-level parts and using the raw FFI bindings directly for everything.

If anyone is interested in redesigning the high-level API I'd be happy to transfer the crate to them, but overall interest in open-al has been very low.

**Comment by sunnystormy** [comment]
Good call! I based this code on a C++ framework I wrote with the same name. Inside of that codebase, I'm using the native methods provided. Switching to the FFI bindings will make the code consistent. Thanks again for your help!

**Comment by jpernst** [comment]
I've just pushed an update that corrects some of the const/mut pointer signatures in alc functions, that should hopefully help a little. I've also deleted the high-level API completely since it's unsound.
